#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>

#define CHAR_INPUT_SPACE_SIZE 34
#define STRING_INPUT_SPACE_SIZE 4
#define BUFFER_SIZE 6

char *charInputSpace = "abcdefghijklmnopqrstuvwxyz{}()[] "; // contains all valid char inputs
char inputChar()
{
  return charInputSpace[rand() % CHAR_INPUT_SPACE_SIZE];
}

// global buffer used for storing random strings generated by inputString fn()
char buf[BUFFER_SIZE] = {0};
char *stringInputSpace = "rest";
char *inputString()
{
  int i;
  for (i = 0; i < BUFFER_SIZE - 1; i++)
  {
    buf[i] = stringInputSpace[rand() % STRING_INPUT_SPACE_SIZE];
  }

  return buf;
}

void testme()
{
  int tcCount = 0;
  char *s;
  char c;
  int state = 0;

  while (1)
  {
    tcCount++;
    c = inputChar();
    s = inputString();
    printf("Iteration %d: c = %c, s = %s, state = %d\n", tcCount, c, s, state);

    if (c == '[' && state == 0)
      state = 1;
    if (c == '(' && state == 1)
      state = 2;
    if (c == '{' && state == 2)
      state = 3;
    if (c == ' ' && state == 3)
      state = 4;
    if (c == 'a' && state == 4)
      state = 5;
    if (c == 'x' && state == 5)
      state = 6;
    if (c == '}' && state == 6)
      state = 7;
    if (c == ')' && state == 7)
      state = 8;
    if (c == ']' && state == 8)
      state = 9;
    if (s[0] == 'r' && s[1] == 'e' && s[2] == 's' && s[3] == 'e' && s[4] == 't' && s[5] == '\0' && state == 9)
    {
      printf("error ");
      exit(200);
    }
  }
}

int main(int argc, char *argv[])
{
  srand(time(NULL));
  testme();
  return 0;
}
